---
  - name: Install template to a file.
    action: template src='{{ file }}' dest='{{ dest }}'
    when: file is defined

  - name: Set permissions on file.
    file: path='{{ dest }}' owner='{{ owner }}' group='{{ group }}' mode='{{ perms }}'
    when: file is defined or url is defined

  - name: Setup the account
    command: /usr/bin/gcloud auth activate-service-account {{ service_account }} --key-file /usr/local/octohost/octo.json
    environment: python_env
